storage:
 value: default
 wizard:
   name: "Storage Configuration"
   kind: cluster_storage

src:
  value: https://github.com/kuberlab-catalog/fastai
  wizard:
    name: "Source Code"
    kind: git

tensorboard:
  value: true
  wizard:
    name: Install Tensorboard
    kind: boolean

dataset:
 value: 'mnist'
 version: '1.0.0'
 workspace: 'kuberlab-demo'
 wizard:
   name: "Dataset configuration"
   kind: dataset

# Pip packages may be specified here in format that pip accepts.
packages: []
